import type { Config } from 'tailwindcss';

const config: Config = {
  darkMode: 'class',
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      fontFamily: {
        headline: ['var(--font-headline)', 'Manrope', 'system-ui', 'sans-serif'],
        display: ['var(--font-display)', 'Inter', 'system-ui', 'sans-serif'],
        body: ['var(--font-display)', 'Inter', 'system-ui', 'sans-serif'],
        lexend: ['var(--font-lexend)', 'Lexend', 'system-ui', 'sans-serif'],
        material: ['var(--font-material-serif)', 'Georgia', 'serif'],
        sora: ['var(--font-sora)', 'Sora', 'system-ui', 'sans-serif'],
      },
      colors: {
        background: 'var(--scribo-bg)',
        'on-background': 'var(--scribo-on-surface)',
        surface: 'var(--scribo-bg)',
        'on-surface': 'var(--scribo-on-surface)',
        'on-surface-variant': 'var(--scribo-on-surface-variant)',
        'surface-variant': '#e2e2e9',
        'surface-bright': 'var(--scribo-surface-bright)',
        'surface-dim': '#dad9e0',
        'surface-container-lowest': 'var(--scribo-surface-lowest)',
        'surface-container-low': 'var(--scribo-surface-low)',
        'surface-container': 'var(--scribo-surface-container)',
        'surface-container-high': 'var(--scribo-surface-high)',
        'surface-container-highest': 'var(--scribo-surface-highest)',
        'inverse-surface': '#2f3035',
        'inverse-on-surface': '#f1f0f7',
        outline: '#747687',
        'outline-variant': 'var(--scribo-outline-variant)',
        /* rgb + <alpha-value> para que primary/20, ring-primary/40 etc. sigam a cor de destaque */
        primary: 'rgb(var(--scribo-primary-rgb) / <alpha-value>)',
        'on-primary': 'rgb(var(--scribo-on-primary-rgb) / <alpha-value>)',
        'primary-container': '#3d68f9',
        'on-primary-container': '#fffbff',
        'primary-fixed': '#dde1ff',
        'primary-fixed-dim': '#b7c4ff',
        'on-primary-fixed': '#001452',
        'on-primary-fixed-variant': '#0038b7',
        'inverse-primary': '#b7c4ff',
        secondary: '#486800',
        'on-secondary': '#ffffff',
        'secondary-container': '#aef500',
        'on-secondary-container': '#4b6d00',
        'secondary-fixed': '#b0f800',
        'secondary-fixed-dim': '#9ad900',
        'on-secondary-fixed': '#131f00',
        'on-secondary-fixed-variant': '#354e00',
        tertiary: '#7f37b7',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#9a52d2',
        'on-tertiary-container': '#fffbff',
        'tertiary-fixed': '#f2daff',
        'tertiary-fixed-dim': '#e1b6ff',
        'on-tertiary-fixed': '#2e004e',
        'on-tertiary-fixed-variant': '#681b9f',
        error: '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        'surface-tint': '#1b4fe1',
        'neon-cyan': '#00f2ff',
        navy: '#0f1823',
        'background-light': '#f6f6f8',
        'background-dark': '#06070d',
        'surface-dark': '#1E293B',
        'border-dark': '#334155',
        'neutral-cream': '#f7f3f0',
        ink: '#0f0f0f',
        paper: '#F9FAFB',
        accent: '#164cdf',
        mute: '#6b6b6b',
        'book-cream': '#f8f6f2',
        'book-blue': '#1e3a5f',
        'book-blue-light': '#2d4a6f',
      },
      borderRadius: {
        DEFAULT: '1rem',
        lg: '2rem',
        xl: '3rem',
        full: '9999px',
      },
    },
  },
  plugins: [],
};

export default config;
